//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menuselect_H
#define METASPRITE_menuselect_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menuselect_TILE_ORIGIN 0
#define menuselect_TILE_W 8
#define menuselect_TILE_H 16
#define menuselect_WIDTH 16
#define menuselect_HEIGHT 16
#define menuselect_TILE_COUNT 4
#define menuselect_PALETTE_COUNT 1
#define menuselect_COLORS_PER_PALETTE 4
#define menuselect_TOTAL_COLORS 4
#define menuselect_PIVOT_X 8
#define menuselect_PIVOT_Y 8
#define menuselect_PIVOT_W 16
#define menuselect_PIVOT_H 16
extern const metasprite_t* const menuselect_metasprites[1];

BANKREF_EXTERN(menuselect)

extern const palette_color_t menuselect_palettes[4];
extern const uint8_t menuselect_tiles[64];

#endif
