//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menubg_H
#define METASPRITE_menubg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menubg_TILE_ORIGIN 0
#define menubg_TILE_W 8
#define menubg_TILE_H 8
#define menubg_WIDTH 160
#define menubg_HEIGHT 144
#define menubg_TILE_COUNT 47
#define menubg_PALETTE_COUNT 1
#define menubg_COLORS_PER_PALETTE 4
#define menubg_TOTAL_COLORS 4
#define menubg_MAP_ATTRIBUTES 0
extern const unsigned char menubg_map[360];
#define menubg_map_attributes menubg_map

BANKREF_EXTERN(menubg)

extern const palette_color_t menubg_palettes[4];
extern const uint8_t menubg_tiles[752];

#endif
