//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splash_H
#define METASPRITE_splash_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splash_TILE_ORIGIN 0
#define splash_TILE_W 8
#define splash_TILE_H 8
#define splash_WIDTH 160
#define splash_HEIGHT 144
#define splash_TILE_COUNT 204
#define splash_PALETTE_COUNT 1
#define splash_COLORS_PER_PALETTE 4
#define splash_TOTAL_COLORS 4
#define splash_MAP_ATTRIBUTES 0
extern const unsigned char splash_map[360];
#define splash_map_attributes splash_map

BANKREF_EXTERN(splash)

extern const palette_color_t splash_palettes[4];
extern const uint8_t splash_tiles[3264];

#endif
