//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_spritemap_world_H
#define METASPRITE_spritemap_world_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spritemap_world_TILE_ORIGIN 0
#define spritemap_world_TILE_W 8
#define spritemap_world_TILE_H 8
#define spritemap_world_WIDTH 160
#define spritemap_world_HEIGHT 144
#define spritemap_world_TILE_COUNT 79
#define spritemap_world_PALETTE_COUNT 1
#define spritemap_world_COLORS_PER_PALETTE 4
#define spritemap_world_TOTAL_COLORS 4
#define spritemap_world_MAP_ATTRIBUTES 0
extern const unsigned char spritemap_world_map[360];
#define spritemap_world_map_attributes spritemap_world_map

BANKREF_EXTERN(spritemap_world)

extern const palette_color_t spritemap_world_palettes[4];
extern const uint8_t spritemap_world_tiles[1264];

#endif
